### ISSUE TITLE
Sprint 1, #S1

### ISSUE THREAD

**Issue by E1Georg** [YWinston/AC#2]
В ходе данного спринта необходимо поднять инфраструктуру в облаке. Задачи добавлены в backlog. Необходимо выполнить [#1] - настроить инфраструктуру и [#2] - настроить среду выполнения.

**Comment by E1Georg** [comment]
Данный спринт был успешно закончен. Был приобретён сервер hetzner, на котором были созданы все условия для работы браузерного приложения приложения(установлена Mysql, Apache2, NodeJS  и т.д).

**Comment by YWinston** [comment]
Данный спринт был успешно закончен. Был приобретён сервер hetzner, на котором были созданы все условия для работы браузерного приложения приложения(установлена Mysql, Apache2, NodeJS и т.д).
